## Site metadata ##

title: The Quantumist
description: A blog about quantum computers, machine learning and more.
name: "The Quantumist"

author: Federico Tiblias, Gilberto Manunza
### Built settings ###

url: "https://the-quantumist.github.io"
baseurl: ""

github_username: the-quantumist

plugins:
  - jekyll-include-cache
  - jekyll-remote-theme
  - jekyll-relative-links
  - jekyll-archives
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
  - jekyll-scholar
  - jekyll-toc

# TOC Settings
toc:
 min_level: 1
 max_level: 3
 list_class: toc
 list_class: toc__list
 sublist_class: toc__sublist

relative_links:
  enabled: true
  collections: true

markdown: kramdown

jekyll-archives:
  enabled: all # []
  layout: archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single_multiple_authors
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "quantum" # "quantum", "air", "aqua", "default", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
